# Generated by Django 4.2 on 2025-02-04 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_3', '0005_time3'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_3_question',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
