# Generated by Django 4.2 on 2025-01-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_hidepractice_hideuser_practice_action_practice_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_2', '0003_module_2_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=1920)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
