# Generated by Django 4.2 on 2025-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0012_alter_certificate_english_alter_certificate_math_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='module1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='module2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='module3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='module4',
            field=models.BooleanField(default=False),
        ),
    ]
