# Generated by Django 4.2 on 2024-12-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_1_question',
            name='image',
        ),
    ]
