# Generated by Django 4.2 on 2025-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0004_alter_module_1_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_1_question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='module1/images/'),
        ),
    ]
