# Generated by Django 4.2 on 2025-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0005_module_1_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_1_question',
            name='module1_time',
            field=models.IntegerField(default=32),
        ),
    ]
