# Generated by Django 4.2 on 2025-01-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0006_module_1_question_module1_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_1_question',
            name='module1_time',
        ),
    ]
