# Generated by Django 4.2 on 2025-01-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_hidepractice_hideuser_practice_action_practice_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_1', '0007_remove_module_1_question_module1_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=32)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
