# Generated by Django 4.2 on 2025-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0008_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='time1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='time1',
            name='time',
            field=models.IntegerField(default=1920),
        ),
    ]
