# Generated by Django 4.2 on 2025-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_2', '0002_alter_module_2_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_2_question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='module2/images/'),
        ),
    ]
