# Generated by Django 4.2 on 2025-02-04 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_2', '0004_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_2_question',
            name='option_input_answer',
        ),
        migrations.AddField(
            model_name='module_2_question',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
