# Generated by Django 4.2 on 2024-12-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0002_remove_module_1_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_1_question',
            name='option_input_answer',
        ),
    ]
