# Generated by Django 4.2 on 2025-02-04 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0009_time1_updated_at_alter_time1_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_1_question',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
