# Generated by Django 4.2 on 2025-01-05 07:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_4_question',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
