# Generated by Django 4.2 on 2025-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_4', '0002_alter_module_4_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_4_question',
            name='option_a',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='module_4_question',
            name='option_b',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='module_4_question',
            name='option_c',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='module_4_question',
            name='option_d',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='module_4_question',
            name='option_input_answer',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='module_4_question',
            name='term',
            field=models.CharField(max_length=2000),
        ),
    ]
