# Generated by Django 4.2 on 2025-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_alter_certificate_math'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='overall',
            field=models.IntegerField(default=0),
        ),
    ]
