# Generated by Django 4.2 on 2024-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
