# Generated by Django 4.2 on 2025-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='english',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
