# Generated by Django 4.2 on 2025-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_math_alter_certificate_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='math',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
