# Generated by Django 4.2 on 2025-01-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_alter_certificate_english_alter_certificate_math_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='english',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
