# Generated by Django 4.2 on 2025-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_alter_certificate_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='english',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='math',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='overall',
            field=models.IntegerField(),
        ),
    ]
