# Generated by Django 4.1.13 on 2024-11-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leakpassword',
            options={'ordering': ['-time']},
        ),
    ]
