# Generated by Django 4.2 on 2024-12-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='end_date',
        ),
    ]
