# Generated by Django 4.2 on 2024-12-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_practice_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='user',
        ),
    ]
