# Generated by Django 4.2 on 2025-01-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_practice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='image',
        ),
    ]
