# Generated by Django 4.2 on 2025-01-05 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_remove_practice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HideUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practice/images/'),
        ),
        migrations.CreateModel(
            name='HideUserPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.hidepractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.hideuser')),
            ],
        ),
        migrations.AddField(
            model_name='hidepractice',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice'),
        ),
    ]
