# Generated by Django 4.2 on 2025-01-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0005_hidepractice_hideuser_practice_action_practice_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module1_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module1_user_ans', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('module1_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='correct.module1_ans')),
            ],
        ),
    ]
