# Generated by Django 4.2 on 2025-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0007_remove_module1_ans_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer1',
            name='user_answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
