# Generated by Django 4.2 on 2025-01-29 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0011_answer1_question_answer2_question_answer3_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='correct_answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer1',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer1',
            name='user_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer2',
            name='correct_answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer2',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer2',
            name='user_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer3',
            name='correct_answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer3',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer3',
            name='user_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer4',
            name='correct_answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer4',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='answer4',
            name='user_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
