# Generated by Django 4.2 on 2025-01-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0005_alter_answer1_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer1',
            name='module1_user_ans',
        ),
        migrations.AddField(
            model_name='module1_ans',
            name='answers',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
