# Generated by Django 4.2 on 2025-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answer1',
        ),
    ]
