# Generated by Django 4.2 on 2025-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0002_rename_answer_answer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer1',
            name='module1_user_ans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
