# Generated by Django 4.2 on 2025-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0006_remove_answer1_module1_user_ans_module1_ans_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module1_ans',
            name='answers',
        ),
    ]
