# Generated by Django 4.2 on 2025-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0008_answer1_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
