# Generated by Django 4.2 on 2025-01-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_hidepractice_hideuser_practice_action_practice_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correct', '0009_alter_answer1_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module4_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module3_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module2_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('module4_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correct.module4_ans')),
            ],
        ),
        migrations.CreateModel(
            name='Answer3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('module3_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correct.module3_ans')),
            ],
        ),
        migrations.CreateModel(
            name='Answer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('module2_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correct.module2_ans')),
            ],
        ),
    ]
